name=CliParser
version=-.1.0
author=Robert Morley <robert.morley@utoronto.ca>
maintainer=Robert Morley <robert.morley@utoronto.ca>
sentence=Command Line Parser for microcontroller.
paragraph=Simple constexpr template command line parser. Will work with C++17 or above.
category=Communication
url=https://github.com/perc-designs/command-parser
architectures=*
